using DocumentFormat.OpenXml.Wordprocessing;

namespace Trans9.Models
{
    public enum shipmentStatus
    {
        IN_PLANT,
        APPROVALPENDING,
        EWAY_EXPIRED,
        DIESEL_SHORTAGE,
        DENT_OR_DAMAGE,
        TOOLKIT_MISSING,
        NOT_IN_RCP,
        TYRE_CUT,
        QUALITY_ISSUE,
        OTHERS,
        IN_YARD,
        ACCIDENT,
        BREAKDOWN,
        CANCEL_SHIPMENT,
        IN_TRANSIT,
        EPOD_PENDING,
        BILLING_DONE,
        PDI_PENDING,
        PDI_HOLD,
        PAINT_SCRATCHES,
        RUSTY_VEHICLE,
        MIRROR_CRACK_MISSING,
        KEY_MISSING,
        CNG_SHORTAGE,
        DEF_SHORTAGE,
        DELIVERED,
        AT_BODY_BUILDER,
        BATTERY_DOWN,
        BREAK_OIL_LEAKAGE,
        PAINT_SCRATCH,
        BUMPER_SCRATCH,
        CAB_BACK_SIDE_DENT,
        CLUTCH_FAIL,
        CNG_SHORT,
        COOLANT_LEAKAGE_FROM_RADIATOR,
        CP_FLAP_DENT,
        DENT_ON_BONET,
        D30_VEHICLE,
        LH_SIDE_DOOR_DENT,
        WIPER_SHORT,
        DEF_CAP_MISSING,
        DENT_ON_FRONT_SHOW,
        DIESAL_EXTRA,
        HOLD_BY_SECURITY,
        DIESAL_LOCK_MISSING,
        DIESAL_SHORT,
        SIESAL_SHORT_AT_HOSTEL,
        DUSTY_VEHICLE,
        RH_SIDE_SCRATCHES,
        INDICATOR_NOT_WORKING,
        RH_AND_LH_SIDE_CAIN_DENT,
        BUMPER_PAINT_SCRATCH,
        BREAK_LIGHT_NOT_WORKING,
        DEF_CAP_AND_WIPER_SHORT,
        DOOR_DENT,
        RH_REAR_TYRE_CUT,
        DIESAL_TANK_SCRATCHES,
        LH_SIDE_TAIL_LAMP_SCRATCHES,
        EXTRA_KMS,
        FRONT_SHOW_DAMAGE,
        FRONT_SHOW_PAINT_ISSUE,
        EXPORT,
        FOOTREST_DAMAGE,
        FRONT_GRILL_DAMAGE,
        REWORK_NOT_DONE_PROPERLY,
        FUSE_COVER_NOT_FITTED_PROPERLY,
        STARTING_PROBLEM,
        LH_DOOR_DENT,
        GEAR_KNOB_MISSING,
        HOLD_BY_QA,
        COLOR_MISMATCH,
        HOLD_BY_SALES_OR_DEALER,
        HOLD_FOR_ONLINE_CRTEM,
        MIRRIR_DAMAGE,
        NOT_LOCATED_IN_HOSTEL,
        OK_IN_HOSTEL,
        OK_IN_RCP,
        RH_SIDE_DOOR_DENT,
        TYRE_PUNCTURE,
        PAINT_SCRACHES_BACK_SIDE,
        REAR_CABIN_DENT,
        JACK_MISSING,
        RH_SIDE_MIRROR_MISSING,
        PDI,
        OIL_LEAKAGE,
        WRONG_PDI_TAG,
        FUSE_COVER_DAMAGE,
        SUPD_DAMAGE,
        RH_SIDE_DENT,
        RH_SIDE_INDICATOR_MISSING,
        TAIL_LAMP_CRACK,
        FOG_LAMP_REFLECTOR_DAMAGE,
        RUPD_DAMAGE,
        RUPD_RUSTY,
        AIR_LEAKAGE,
        ENG_STOP,
        WIRING_HARNESS_ISSUE,
        WIPER_NOT_WORKING
    }


    public enum payment { paid, deleted }
    public enum driverStatus { active, blocked, deleted }
    public enum ewayStatus { hold, expired, extended }
    public enum comonStatus { active, deleted }
    public enum DealerType { BB, DLR, ESS, NEPAL, RSO }

    public enum Actions
    {
        shipment,
        plantout,
        marching,
        payment,
        closing,
        billing,
        incidence,
        all,
        auth
    }

    public enum PageGroup { billing, incidence, master, permit, report, transact, employee }
}